FROM centos:7
MAINTAINER Adriano Vieira <adriano.svieira at gmail.com>
# install base packs
RUN rpm -ivh https://github.com/spf13/hugo/releases/download/v0.16/hugo-0.16-2.el6.x86_64.rpm;

ENV HUGO_BASE_URL http://localhost:1313
ENV HUGO_BUILD_DRAFTS --buildDrafts

EXPOSE 1313

ARG SITE_RELEASE=bsbv0.2
# first off all download SITE_RELEASE (or branch)
#e.g. curl -LOk https://github.com/adrianovieira/devopsdays-web/archive/${SITE_RELEASE}.tar.gz
ADD ${SITE_RELEASE}.tar.gz /var/www/html/

WORKDIR /var/www/html/devopsdays-web-${SITE_RELEASE}

# run Hugo site
CMD hugo server --watch=false ${HUGO_BUILD_DRAFTS} --bind=0.0.0.0 -b ${HUGO_BASE_URL} --port 1313 --destination="/var/www/html/site_watch"
